@startuml

left to right direction
skinparam packageStyle rectangle

actor Utilisateur
actor Participant
actor Marchand

rectangle "Système Interopérabilité" {
  usecase "UC-001 : Création d’Alias" as UC1
  usecase "UC-002: Recherche d’Alias" as UC2
  usecase "UC-003: Transfert P2P" as UC3
  usecase "UC-004: Paiement Marchand" as UC4
  usecase "UC-005: Test de Connectivité vers PI" as UC5
  usecase "UC-006: Sponsorisation de Participant Indirect" as UC6
  usecase "UC-007: Gestion de Compte des Participants" as UC7
}

Marchand -- UC4

Utilisateur -- UC1
Utilisateur -- UC2
Utilisateur -- UC4
Utilisateur -- UC3

Participant -- UC3
Participant -- UC4

Participant -- UC5
Participant -- UC6
Participant -- UC7

@enduml